//BASE_URL

export const BASE_URL = "https://visualresume-api.herokuapp.com";

//Authentication Types
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";

export const RESUME_ID = "RESUME_ID";
export const RESET_FORM = "RESET_FORM";

export const REQUEST_RESUME = "REQUEST_RESUME";
export const REQUEST_RESUME_USER = "REQUEST_RESUME_USER";
export const REQUEST_USER = "REQUEST_USER";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_PROJECTS = "UPDATE_PROJECTS";
export const UPDATE_SKILLS = "UPDATE_SKILLS";
export const UPDATE_SOCIALMEDIA = "UPDATE_SOCIALMEDIA";
