//Authentication Types
export const AUTHENTICATION_REQUEST = "AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const LOGOUT = "LOGOUT";

export const RESET_FORM = "RESET_FORM";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const REQUEST_RESUME = "REQUEST_RESUME";
